####################################
## DEPLOYMENT_REPO-VARIABLES.YAML ##
####################################
deployment:
  viya4:
    # Get this information from your POC Viya Order - https://apiportal.sas.com/get-started
    cadencename: 'stable'
    cadenceversion: '2021.2.5'
    ordernumber: '99XXXX'
    orderapikey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    orderapisecret: 'XXXXXXXXXXXXXXXX'
    # This information corresponds to the SAS Supported azure iac GIT repo
    # https://github.com/sassoftware/viya4-iac-azure
    iacazure:
      tag: '4.5.0'
    # This information corresponds to the SAS supported azure viya deployment GIT repo
    # https://github.com/sassoftware/viya4-deployment
    viya4deployment:
      versiontag: '4.11.0'
